name: Terraform format check

inputs:
  version:
    description: Terraform version.
    required: true

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ inputs.version }}
        terraform_wrapper: false
    - name: Terraform fmt
      run: terraform fmt -check -diff -recursive
      shell: bash
